# Generated by Django 5.0.4 on 2024-05-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_platform', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='mycourses', to='el_platform.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='TEACHER', max_length=50),
        ),
    ]
