# Generated by Django 5.0.4 on 2024-05-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_platform', '0001_initial'),
        ('users', '0002_user_courses_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='mycourses', to='el_platform.course'),
        ),
    ]
