# Generated by Django 5.0.4 on 2024-05-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_platform', '0003_remove_course_users'),
        ('users', '0004_remove_user_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='el_platform.course'),
        ),
    ]
