# Generated by Django 5.0.4 on 2024-05-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_platform', '0003_remove_course_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='el_platform.course'),
        ),
    ]
